# Cleaning data for Naihville Housing

## Created by Garry Anggadita

#### Objectives 
The objective of this project is to clean up Nashville Housing Data from 2013 to 2019. For this project, I gonna handling missing values, structural errors, filter unwanted column tables, and remove duplicates to give a clean dataset for further Exploratory Data Analysis. Without any further ado, let's check it out!

In [16]:
import pandas as pd
import numpy as np

from datetime import datetime

In [17]:
NH = pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Documents\\Nashville Housing\\nashville_housing.csv")

In [18]:
NH.head(5)

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE","April 9, 2013",240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE","June 10, 2014",366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE","September 26, 2016",435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE","January 29, 2016",255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE","October 10, 2014",278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0

## Remove Null Data

In [5]:
NH[NH['PropertyAddress'].isnull()]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
159,43076,025 07 0 031.00,SINGLE FAMILY,NaN,"January 15, 2016",179900,20160120-0005776,No,"COSTNER, FRED & CAROLYN","410 ROSEHILL CT, GOODLETTSVILLE, TN",0.96,CITY OF GOODLETTSVILLE,30000.0,70000.0,100000.0,1964.0,3.0,1.0,0.0
223,39432,026 01 0 069.00,VACANT RESIDENTIAL LAND,NaN,"October 23, 2015",153000,20151028-0109602,No,"SHACKLEFORD, MICHAEL C., JR.","141 TWO MILE PIKE, GOODLETTSVILLE, TN",0.17,CITY OF GOODLETTSVILLE,21100.0,121600.0,142700.0,2015.0,3.0,2.0,0.0
246,45290,026 05 0 017.00,SINGLE FAMILY,NaN,"March 29, 2016",155000,20160330-0029941,No,"TRIPP, MARVIN S. & DEBORAH YOUNG","208 EAST AVE, GOODLETTSVILLE, TN",0.20,CITY OF GOODLETTSVILLE,21100.0,130200.0,151300.0,2008.0,3.0,2.0,0.0
305,53147,026 06 0A 038.00,RESIDENTIAL CONDO,NaN,"August 25, 2016",144900,20160831-0091567,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,43080,033 06 0 041.00,SINGLE FAMILY,NaN,"January 4, 2016",170000,20160107-0001526,No,"FRANK, ZACHARY & NIKI","1129 CAMPBELL RD, GOODLETTSVILLE, TN",0.24,GENERAL SERVICES DISTRICT,35000.0,110500.0,145500.0,2000.0,3.0,2.0,0.0
533,45295,033 06 0A 002.00,SINGLE FAMILY,NaN,"March 29, 2016",210000,20160331-0030709,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
665,48731,033 15 0 123.00,SINGLE FAMILY,NaN,"May 5, 2016",199900,20160506-0045368,No,"COLEMAN, AARON A. & CECIL, CORRIE J.","438 W CAMPBELL RD, GOODLETTSVILLE, TN",1.39,GENERAL SERVICES DISTRICT,45000.0,90300.0,135300.0,1954.0,2.0,1.0,0.0
858,36531,034 03 0 059.00,SINGLE FAMILY,NaN,"August 13, 2015",245000,20150819-0083759,No,"DILICK, JOHN MARK & ANNETTE A.","2117 PAULA DR, MADISON, TN",1.01,GENERAL SERVICES DISTRICT,32000.0,170000.0,228300.0,1964.0,4.0,3.0,0.0
1043,46919,034 07 0B 015.00,VACANT RESIDENTIAL LAND,NaN,"April 27, 2016",40000,20160304-0020905,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1176,44264,034 16 0A 004.00,VACANT RESIDENTIAL LAND,NaN,"February 4, 2016",130000,20160205-0011327,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1262,45298,041 03 0A 100.00,SINGLE FAMILY,NaN,"March 18, 2016",170000,20160322-0027048,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1642,40678,042 13 0 075.00,SINGLE FAMILY,NaN,"November 30, 2015",208000,20151209-0123831,No,"SADOWSKY, ERIC C. & LISA D.","222 FOXBORO DR, MADISON, TN",1.01,GENERAL SERVICES DISTRICT,30000.0,100000.0,130000.0,1967.0,3.0,1.0,1.0
1782,47293,043 04 0 014.00,SINGLE FAMILY,NaN,"April 29, 2016",190000,20160503-0043576,No,"CRIPPS, WILLIE S. JR. & GINEA M.","112 HILLER DR, OLD HICKORY, TN",0.29,GENERAL SERVICES DISTRICT,17000.0,143700.0,173600.0,1956.0,4.0,2.0,1.0
1921,22775,043 09 0 074.00,VACANT RESIDENTIAL LAND,NaN,"October 27, 2014",151000,20141028-0099094,Yes,"BREWER HOLDINGS, LLC","213 B LOVELL ST, MADISON, TN",0.15,GENERAL SERVICES DISTRICT,18000.0,115600.0,133600.0,2015.0,3.0,2.0,0.0
2110,45349,043 13 0 308.00,SINGLE FAMILY,NaN,"March 31, 2016",155000,20160405-0032445,No,"JACKSON, ADAM L. & MOORE, MARY A.","224 HICKORY ST, MADISON, TN",0.16,GENERAL SERVICES DISTRICT,16000.0,65900.0,81900.0,1940.0,2.0,1.0,0.0
2362,50927,044 05 0 135.00,SINGLE FAMILY,NaN,"June 15, 2016",160000,20160617-0061987,No,"SMITH, WARREN & MARTHA","202 KEETON AVE, OLD HICKORY, TN",0.12,GENERAL SERVICES DISTRICT,19000.0,102700.0,121700.0,2015.0,4.0,2.0,0.0
3434,3299,052 01 0 296.00,SINGLE FAMILY,NaN,"May 31, 2013",79370,20130620-0063114,No,"KIRBY, WILLIAM E. JR","726 IDLEWILD DR, MADISON, TN",0.22,GENERAL SERVICES DISTRICT,16000.0,60800.0,76800.0,1957.0,2.0,1.0,0.0
3681,43151,052 08 0A 320.00,SINGLE FAMILY,NaN,"January 15, 2016",150000,20160119-0004918,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19984,49886,092 06 0 273.00,SINGLE FAMILY,NaN,"June 21, 2016",186000,20160705-0068281,No,"SOLAVA, RACHEL LYNN","2721 HERMAN ST, NASHVILLE, TN",0.17,URBAN SERVICES DISTRICT,9000.0,63200.0,72200.0,1987.0,2.0,1.0,1.0
19986,27140,092 06 0 282.00,SINGLE FAMILY,NaN,"February 20, 2015",41500,20150224-0015900,No,PROSPERITAS PARTNERS LLC,"815 31ST AVE N, NASHVILLE, TN",0.17,URBAN SERVICES DISTRICT,13000.0,49400.0,62400.0,1960.0,2.0,1.0,0.0
20328,11478,092 13 0 322.00,SINGLE FAMILY,NaN,"January 17, 2014",269500,20140122-0006168,No,"WIGGINS, MATHEW L. & GOOD, KENDRA A.","237 37TH AVE N, NASHVILLE, TN",0.34,URBAN SERVICES DISTRICT,91000.0,107100.0,198100.0,1945.0,2.0,1.0,0.0
20332,32385,092 13 0 339.00,SINGLE FAMILY,NaN,"June 5, 2015",450000,20150618-0058311,No,"JUMPER, NICOLE","311 35TH AVE N, NASHVILLE, TN",0.16,URBAN SERVICES DISTRICT,65000.0,365300.0,430300.0,2015.0,3.0,3.0,1.0
21129,8126,093 08 0 054.00,SINGLE FAMILY,NaN,"September 20, 2013",25000,20130923-0099666,N,"CRAWFORD, CHRISTOPHER C. & BOBBIE LEANN","700 GLENVIEW DR, NASHVILLE, TN",0.21,URBAN SERVICES DISTRICT,25000.0,236800.0,261800.0,2015.0,3.0,2.0,1.0
29124,45774,107 13 0 107.00,SINGLE FAMILY,NaN,"March 28, 2016",169900,20160330-0030078,No,"GROOMS, MICAH & CASEY","1205 THOMPSON PL, NASHVILLE, TN",0.39,URBAN SERVICES DISTRICT,17000.0,75600.0,96200.0,1949.0,3.0,1.0,0.0
29332,14753,108 07 0A 026.00,RESIDENTIAL CONDO,NaN,"April 15, 2014",79900,20140416-0031777,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29894,15886,109 04 0A 080.00,VACANT RES LAND,NaN,"May 13, 2014",255590,20140514-0041276,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30087,24197,110 03 0A 061.00,SINGLE FAMILY,NaN,"November 19, 2014",269750,20141120-0106962,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30192,51930,113 14 0A 002.00,VACANT RESIDENTIAL LAND,NaN,"July 5, 2016",133000,20160707-0069375,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30540,51703,114 15 0A 030.00,RESIDENTIAL CONDO,NaN,"July 8, 2016",343235,20160713-0071757,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

From This data we know that 29 row have a null Property Address , so we are gonna drop this row because we need the Property Address for future analysis and it must not be null

In [20]:
NH=NH.dropna(subset=['PropertyAddress'])

In [21]:
NH[NH['PropertyAddress'].isnull()]

Empty DataFrame
Columns: [UniqueID , ParcelID, LandUse, PropertyAddress, SaleDate, SalePrice, LegalReference, SoldAsVacant, OwnerName, OwnerAddress, Acreage, TaxDistrict, LandValue, BuildingValue, TotalValue, YearBuilt, Bedrooms, FullBath, HalfBath]
Index: []

# Reformat Structural Error

For structural reformatting, I gonna split the property address and owner addresses into address and city. Then change the data type of the Sale Date column and reformatting the 'SalePrice' structure

In [22]:
NH['address']=NH['PropertyAddress'].str.split(',').str[0]
NH['city']=NH['PropertyAddress'].str.split(',').str[1]

In [23]:
NH.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,...,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,address,city
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE","April 9, 2013",240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE","June 10, 2014",366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE","September 26, 2016",435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE","January 29, 2016",255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE","October 10, 2014",278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",...,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE

In [24]:
NH= NH.drop('PropertyAddress',axis=1)

In [25]:
NH.head()

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,address,city
0,2045,007 00 0 125.00,SINGLE FAMILY,"April 9, 2013",240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE
1,16918,007 00 0 130.00,SINGLE FAMILY,"June 10, 2014",366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE
2,54582,007 00 0 138.00,SINGLE FAMILY,"September 26, 2016",435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE
3,43070,007 00 0 143.00,SINGLE FAMILY,"January 29, 2016",255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE
4,22714,007 00 0 149.00,SINGLE FAMILY,"October 10, 2014",278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE

In [26]:
NH['OwnerAddressSplit'] =NH['OwnerAddress'].str.split(',').str[0]
NH['OwnerCity'] =NH['OwnerAddress'].str.split(',').str[1]
NH['OwnerState'] =NH['OwnerAddress'].str.split(',').str[2]

In [27]:
NH.head()

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,address,city,OwnerAddressSplit,OwnerCity,OwnerState
0,2045,007 00 0 125.00,SINGLE FAMILY,"April 9, 2013",240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,...,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,"June 10, 2014",366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,...,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN
2,54582,007 00 0 138.00,SINGLE FAMILY,"September 26, 2016",435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,...,298000.0,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE,1864 FOX CHASE DR,GOODLETTSVILLE,TN
3,43070,007 00 0 143.00,SINGLE FAMILY,"January 29, 2016",255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,...,197300.0,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE,1853 FOX CHASE DR,GOODLETTSVILLE,TN
4,22714,007 00 0 149.00,SINGLE FAMILY,"October 10, 2014",278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,...,202300.0,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE,1829 FOX CHASE DR,GOODLETTSVILLE,TN

In [28]:
NH= NH.drop('OwnerAddress',axis=1)

In [16]:
NH

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,address,city,OwnerAddressSplit,OwnerCity,OwnerState
0,2045,007 00 0 125.00,SINGLE FAMILY,"April 9, 2013",240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",2.3,GENERAL SERVICES DISTRICT,...,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,"June 10, 2014",366000,20140619-0053768,No,"BONER, CHARLES & LESLIE",3.5,GENERAL SERVICES DISTRICT,...,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN
2,54582,007 00 0 138.00,SINGLE FAMILY,"September 26, 2016",435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE",2.9,GENERAL SERVICES DISTRICT,...,298000.0,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE,1864 FOX CHASE DR,GOODLETTSVILLE,TN
3,43070,007 00 0 143.00,SINGLE FAMILY,"January 29, 2016",255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.",2.6,GENERAL SERVICES DISTRICT,...,197300.0,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE,1853 FOX CHASE DR,GOODLETTSVILLE,TN
4,22714,007 00 0 149.00,SINGLE FAMILY,"October 10, 2014",278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.",2.0,GENERAL SERVICES DISTRICT,...,202300.0,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE,1829 FOX CHASE DR,GOODLETTSVILLE,TN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"May 27, 2015",157500,20150608-0053286,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1435 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"March 2, 2015",145000,20150304-0019013,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1423 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"August 16, 2016",234611,20160819-0087214,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1804 GRACE POINT LN,NOLENSVILLE,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"September 7, 2016",93844,20160919-0098411,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1709 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"September 7, 2016",93844,20160919-0098411,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1713 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN

In [29]:
NH['SaleDate']=pd.to_datetime(NH['SaleDate'])

In [30]:
NH['SaleDate']

0       2013-04-09
1       2014-06-10
2       2016-09-26
3       2016-01-29
4       2014-10-10
           ...
56472   2015-05-27
56473   2015-03-02
56474   2016-08-16
56475   2016-09-07
56476   2016-09-07
Name: SaleDate, Length: 56448, dtype: datetime64[ns]

In [31]:
NH['SaleYear']= NH['SaleDate'].dt.year

In [32]:
NH

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,...,YearBuilt,Bedrooms,FullBath,HalfBath,address,city,OwnerAddressSplit,OwnerCity,OwnerState,SaleYear
0,2045,007 00 0 125.00,SINGLE FAMILY,2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",2.3,GENERAL SERVICES DISTRICT,...,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN,2013
1,16918,007 00 0 130.00,SINGLE FAMILY,2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE",3.5,GENERAL SERVICES DISTRICT,...,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN,2014
2,54582,007 00 0 138.00,SINGLE FAMILY,2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE",2.9,GENERAL SERVICES DISTRICT,...,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE,1864 FOX CHASE DR,GOODLETTSVILLE,TN,2016
3,43070,007 00 0 143.00,SINGLE FAMILY,2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.",2.6,GENERAL SERVICES DISTRICT,...,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE,1853 FOX CHASE DR,GOODLETTSVILLE,TN,2016
4,22714,007 00 0 149.00,SINGLE FAMILY,2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.",2.0,GENERAL SERVICES DISTRICT,...,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE,1829 FOX CHASE DR,GOODLETTSVILLE,TN,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1435 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN,2015
56473,27707,188 10 0A 107.00,SINGLE FAMILY,2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1423 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN,2015
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1804 GRACE POINT LN,NOLENSVILLE,NaN,NaN,NaN,2016
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1709 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN,2016
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1713 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN,2016

Change 'N' and 'Y' to "No" or "Yes" in 'SoldAsVacant' column

In [33]:
pd.unique(NH['SoldAsVacant'])

array(['No', 'N', 'Yes', 'Y'], dtype=object)

In [34]:
NH['SoldAsVacant']= NH['SoldAsVacant'].replace(['N','Y'],['No','Yes'])

In [36]:
pd.unique(NH['SoldAsVacant'])

array(['No', 'Yes'], dtype=object)

# Change data type

In this 'SalePrice' column , we need to change data type from string to integer so we could make analysis ,but there's some obstacles where saleprice format is in '100,000' and '$100000' so we will change the format first then change the data type

In [78]:
pd.to_numeric(NH['SalePrice'])

ValueError: Unable to parse string "120,000" at position 186

In [37]:
NH['SalePrice']=pd.Series(NH['SalePrice']).str.replace(",","")
NH['SalePrice']=pd.Series(NH['SalePrice']).str.replace("$","")

In [38]:
NH['SalePrice']=pd.to_numeric(NH['SalePrice'])

In [30]:
NH.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56448 entries, 0 to 56476
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   UniqueID           56448 non-null  int64
 1   ParcelID           56448 non-null  object
 2   LandUse            56448 non-null  object
 3   SaleDate           56448 non-null  datetime64[ns]
 4   SalePrice          56448 non-null  int64
 5   LegalReference     56448 non-null  object
 6   SoldAsVacant       56448 non-null  object
 7   OwnerName          25243 non-null  object
 8   Acreage            25997 non-null  float64
 9   TaxDistrict        25997 non-null  object
 10  LandValue          25997 non-null  float64
 11  BuildingValue      25997 non-null  float64
 12  TotalValue         25997 non-null  float64
 13  YearBuilt          24145 non-null  float64
 14  Bedrooms           24139 non-null  float64
 15  FullBath           24257 non-null  float64
 16  HalfBath           24126 non-null  float64
 17  address            56448 non-null  object
 18  city               56448 non-null  object
 19  OwnerAddressSplit  25997 non-null  object
 20  OwnerCity          25997 non-null  object
 21  OwnerState         25997 non-null  object
 22  SaleYear           56448 non-null  int32
dtypes: datetime64[ns](1), float64(8), int32(1), int64(2), object(11)
memory usage: 10.1+ MB

# Drop Duplicates

In [33]:
NH[NH.duplicated(['address','SalePrice','SaleDate','LegalReference'])]

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,...,YearBuilt,Bedrooms,FullBath,HalfBath,address,city,OwnerAddressSplit,OwnerCity,OwnerState,SaleYear
57,4515,018 00 0 096.00,VACANT RES LAND,2013-06-28,250000,20130709-0070947,No,"BUCHANAN, DONALD W. & SANDRA R.",3.00,CITY OF GOODLETTSVILLE,...,NaN,NaN,NaN,NaN,0 BRICK CHURCH PIKE,GOODLETTSVILLE,0 BRICK CHURCH PIKE,GOODLETTSVILLE,TN,2013
1854,52017,043 06 0 006.00,VACANT RESIDENTIAL LAND,2016-07-20,55000,20160722-0075671,Yes,"B & N CONSTRUCTION, LLC",1.31,GENERAL SERVICES DISTRICT,...,NaN,NaN,NaN,NaN,0 ANDERSON LN,MADISON,0 ANDERSON LN,MADISON,TN,2016
1971,54651,043 10 0A 015.00,RESIDENTIAL CONDO,2016-09-14,123000,20160919-0098102,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2016
1972,54652,043 10 0A 024.00,RESIDENTIAL CONDO,2016-09-14,123000,20160919-0098102,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2016
1980,34809,043 10 0A 040.00,RESIDENTIAL CONDO,2015-07-10,128000,20150715-0068833,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54791,1630,181 02 0A 267.00,VACANT RES LAND,2013-04-30,366800,20130502-0044406,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8605 PECKHAM LN,ANTIOCH,NaN,NaN,NaN,2013
54792,1631,181 02 0A 268.00,VACANT RES LAND,2013-04-30,366800,20130502-0044406,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8605 PECKHAM LN,ANTIOCH,NaN,NaN,NaN,2013
54793,1632,181 02 0A 269.00,VACANT RES LAND,2013-04-30,366800,20130502-0044406,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8605 PECKHAM LN,ANTIOCH,NaN,NaN,NaN,2013
54795,1633,181 02 0A 270.00,VACANT RES LAND,2013-04-30,366800,20130502-0044406,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8605 PECKHAM LN,ANTIOCH,NaN,NaN,NaN,2013
54796,1634,181 02 0A 271.00,VACANT RES LAND,2013-04-30,366800,20130502-0044406,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8605 PECKHAM LN,ANTIOCH,NaN,NaN,NaN,2013

Based on data there's 991 duplicates row which is gonna be drop

In [50]:
NH.iloc[1971:1976]

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,...,YearBuilt,Bedrooms,FullBath,HalfBath,address,city,OwnerAddressSplit,OwnerCity,OwnerState,SaleYear
1994,34813,043 10 0A 067.00,RESIDENTIAL CONDO,2015-07-10,45000,20150715-0068830,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2015
1995,33087,043 10 0A 069.00,RESIDENTIAL CONDO,2015-06-18,40000,20150623-0059953,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2015
1996,39481,043 10 0A 070.00,RESIDENTIAL CONDO,2015-10-16,45000,20151021-0107086,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2015
1997,44113,043 10 0A 071.00,RESIDENTIAL CONDO,2016-02-17,35000,20160218-0015610,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2016
1998,2104,043 10 0A 074.00,RESIDENTIAL CONDO,2013-04-05,41000,20130408-0034400,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,555 N DUPONT AVE,MADISON,NaN,NaN,NaN,2013

In [47]:
NH=NH.drop_duplicates(['address','SalePrice','SaleDate','LegalReference'])

In [48]:
NH

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,...,YearBuilt,Bedrooms,FullBath,HalfBath,address,city,OwnerAddressSplit,OwnerCity,OwnerState,SaleYear
0,2045,007 00 0 125.00,SINGLE FAMILY,2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",2.3,GENERAL SERVICES DISTRICT,...,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN,2013
1,16918,007 00 0 130.00,SINGLE FAMILY,2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE",3.5,GENERAL SERVICES DISTRICT,...,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN,2014
2,54582,007 00 0 138.00,SINGLE FAMILY,2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE",2.9,GENERAL SERVICES DISTRICT,...,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE,1864 FOX CHASE DR,GOODLETTSVILLE,TN,2016
3,43070,007 00 0 143.00,SINGLE FAMILY,2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.",2.6,GENERAL SERVICES DISTRICT,...,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE,1853 FOX CHASE DR,GOODLETTSVILLE,TN,2016
4,22714,007 00 0 149.00,SINGLE FAMILY,2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.",2.0,GENERAL SERVICES DISTRICT,...,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE,1829 FOX CHASE DR,GOODLETTSVILLE,TN,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1435 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN,2015
56473,27707,188 10 0A 107.00,SINGLE FAMILY,2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1423 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN,2015
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1804 GRACE POINT LN,NOLENSVILLE,NaN,NaN,NaN,2016
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1709 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN,2016
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1713 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN,2016

# Drop Unwanted Column

In [52]:
NH= NH.drop(['LegalReference','OwnerName','TaxDistrict'],axis=1)

In [53]:
NH

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,SoldAsVacant,Acreage,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,address,city,OwnerAddressSplit,OwnerCity,OwnerState,SaleYear
0,2045,007 00 0 125.00,SINGLE FAMILY,2013-04-09,240000,No,2.3,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN,2013
1,16918,007 00 0 130.00,SINGLE FAMILY,2014-06-10,366000,No,3.5,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN,2014
2,54582,007 00 0 138.00,SINGLE FAMILY,2016-09-26,435000,No,2.9,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR,GOODLETTSVILLE,1864 FOX CHASE DR,GOODLETTSVILLE,TN,2016
3,43070,007 00 0 143.00,SINGLE FAMILY,2016-01-29,255000,No,2.6,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR,GOODLETTSVILLE,1853 FOX CHASE DR,GOODLETTSVILLE,TN,2016
4,22714,007 00 0 149.00,SINGLE FAMILY,2014-10-10,278000,No,2.0,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR,GOODLETTSVILLE,1829 FOX CHASE DR,GOODLETTSVILLE,TN,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,2015-05-27,157500,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1435 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN,2015
56473,27707,188 10 0A 107.00,SINGLE FAMILY,2015-03-02,145000,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1423 WINDING CREEK DR,NOLENSVILLE,NaN,NaN,NaN,2015
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,2016-08-16,234611,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1804 GRACE POINT LN,NOLENSVILLE,NaN,NaN,NaN,2016
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,2016-09-07,93844,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1709 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN,2016
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,2016-09-07,93844,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1713 PARK TERRACE LN,NOLENSVILLE,NaN,NaN,NaN,2016